apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
    app.kubernetes.io/component: frontend
    {{- include "devops-employee.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}

  selector:
    app: {{ .Values.frontend.name }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
